version: "3.3"
services:
  react-build:
    build:
      context: ../../
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        npm run build --prop
    volumes:
      - ../..:/app
      - .env
      - /app/node_modules
    environment:
      - REACT_APP_ENV
    restart: "no"

