version: "3.3"
services:
  react-build:
    build:
      context: ../../
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        npm start
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ../..:/app
      - .env
      - /app/node_modules
    environment:
      - REACT_APP_ENV
      - REACT_APP_API_BASE_URL
      - REACT_APP_PUBLIC_URL
      - PORT
      - SKIP_FREFLIGHT_CHECK
    restart: "no"

